export const regionMappings = {
    // Latin America (LATAM)
    'Mexico': 'LATAM',
    'Brazil': 'LATAM',
    'Argentina': 'LATAM',
    'Chile': 'LATAM',
    'Colombia': 'LATAM',
    'Peru': 'LATAM',
    'Ecuador': 'LATAM',
    'Bolivia': 'LATAM',
    'Paraguay': 'LATAM',
    'Uruguay': 'LATAM',
    'Venezuela': 'LATAM',
    'Costa Rica': 'LATAM',
    'Cuba': 'LATAM',
    'Dominican Republic': 'LATAM',
    'Guatemala': 'LATAM',
    'Honduras': 'LATAM',
    'Nicaragua': 'LATAM',
    'Panama': 'LATAM',
    // Single Euro Payments Area (SEPA)
    'Germany': 'SEPA',
    'France': 'SEPA',
    'Spain': 'SEPA',
    'Italy': 'SEPA',
    'Netherlands': 'SEPA',
    'Belgium': 'SEPA',
    'Austria': 'SEPA',
    'Portugal': 'SEPA',
    'Ireland': 'SEPA',
    'Luxembourg': 'SEPA',
    'Greece': 'SEPA',
    'Finland': 'SEPA',
    'Sweden': 'SEPA',
    'Denmark': 'SEPA',
    'Poland': 'SEPA',
    'Hungary': 'SEPA',
    'Czech Republic': 'SEPA',
    'Slovakia': 'SEPA',
    // ASEAN (Association of Southeast Asian Nations)
    'Thailand': 'ASEAN',
    'Indonesia': 'ASEAN',
    'Malaysia': 'ASEAN',
    'Vietnam': 'ASEAN',
    'Philippines': 'ASEAN',
    'Singapore': 'ASEAN',
    'Myanmar': 'ASEAN',
    'Cambodia': 'ASEAN',
    'Laos': 'ASEAN',
    'Brunei': 'ASEAN',
    // EAC (East African Community)
    'Kenya': 'EAC',
    'Tanzania': 'EAC',
    'Uganda': 'EAC',
    'Rwanda': 'EAC',
    'Burundi': 'EAC',
    'South Sudan': 'EAC',
    // GCC (Gulf Cooperation Council)
    'Saudi Arabia': 'GCC',
    'United Arab Emirates': 'GCC',
    'Qatar': 'GCC',
    'Kuwait': 'GCC',
    'Oman': 'GCC',
    'Bahrain': 'GCC',
    // CARICOM (Caribbean Community)
    'Jamaica': 'CARICOM',
    'Trinidad and Tobago': 'CARICOM',
    'Barbados': 'CARICOM',
    'Bahamas': 'CARICOM',
    'Guyana': 'CARICOM',
    'Suriname': 'CARICOM',
    'Grenada': 'CARICOM',
    'Saint Lucia': 'CARICOM',
    'Saint Vincent and the Grenadines': 'CARICOM',
    'Antigua and Barbuda': 'CARICOM',
    'Dominica': 'CARICOM',
    'Belize': 'CARICOM',
    'Saint Kitts and Nevis': 'CARICOM',
    // CEFTA (Central European Free Trade Agreement)
    'Albania': 'CEFTA',
    'Bosnia and Herzegovina': 'CEFTA',
    'North Macedonia': 'CEFTA',
    'Montenegro': 'CEFTA',
    'Serbia': 'CEFTA',
    'Kosovo': 'CEFTA',
    // Pacific Islands Forum
    'Australia': 'PIF',
    'New Zealand': 'PIF',
    'Fiji': 'PIF',
    'Papua New Guinea': 'PIF',
    'Samoa': 'PIF',
    'Solomon Islands': 'PIF',
    'Vanuatu': 'PIF',
    'Tonga': 'PIF',
    'Kiribati': 'PIF',
    'Tuvalu': 'PIF',
    'Nauru': 'PIF',
    'Marshall Islands': 'PIF',
    'Palau': 'PIF'
    // Add additional cases for other regions as needed
};

export const regionTagsOptions = ['LATAM', 'SEPA', 'ASEAN', 'EAC', 'GCC', 'CARICOM', 'CEFTA', 'PIF'];